package converter;

public enum Currency {
    USD("usd", "U.S.Dollar"),
    EUR("eur", "Euro"),
    GBP("gbp", "U.K.Pound Sterling"),
    AUD("aud", "Australian Dollar"),
    CAD("cad", "Canadian Dollar"),
    JPY("jpy", "Japanese Yen"),
    CHF("chf", "Swiss Franc"),
    KMF("kmf", "Comoro franc"),
    AFN("afn", "Afghan afghani"),
    ALL("all", "Albanian lek"),
    DZD("dzd", "Algerian Dinar"),
    AOA("aoa", "Angolan kwanza"),
    ARS("ars", "Argentine Peso"),
    AMD("amd", "Armenia Dram"),
    AWG("awg", "Aruban florin"),
    AZN("azn", "Azerbaijan Manat"),
    BSD("bsd", "Bahamian Dollar"),
    BHD("bhd", "Bahrain Dinar"),
    BDT("bdt", "Bangladeshi taka"),
    BBD("bbd", "Barbadian Dollar"),
    BYR("byr", "Belarussian Ruble"),
    BYN("byn", "Belarussian Ruble"),
    BZD("bzd", "Belize dollar"),
    BOB("bob", "Bolivian Boliviano"),
    BAM("bam", "Bosnia and Herzegovina convertible mark"),
    BWP("bwp", "Botswana Pula"),
    BRL("brl", "Brazilian Real"),
    BND("bnd", "Brunei Dollar"),
    BGN("bgn", "Bulgarian Lev"),
    BIF("bif", "Burundian franc"),
    KHR("khr", "Cambodian riel"),
    CVE("cve", "Cape Verde escudo"),
    XAF("xaf", "Central African CFA Franc"),
    XPF("xpf", "CFP Franc"),
    CLP("clp", "Chilean Peso"),
    CNY("cny", "Chinese Yuan"),
    COP("cop", "Colombian Peso"),
    CDF("cdf", "Congolese franc"),
    CRC("crc", "Costa Rican Colón"),
    HRK("hrk", "Croatian Kuna"),
    CUP("cup", "Cuban peso"),
    CZK("czk", "Czech Koruna"),
    DKK("dkk", "Danish Krone"),
    DJF("djf", "Djiboutian franc"),
    DOP("dop", "Dominican Peso"),
    XCD("xcd", "East Caribbean Dollar"),
    EGP("egp", "Egyptian Pound"),
    ERN("ern", "Eritrean nakfa"),
    ETB("etb", "Ethiopian birr"),
    FJD("fjd", "Fiji Dollar"),
    GMD("gmd", "Gambian dalasi"),
    GEL("gel", "Georgian lari"),
    GHS("ghs", "Ghanaian Cedi"),
    GIP("gip", "Gibraltar pound"),
    GTQ("gtq", "Guatemalan Quetzal"),
    GNF("gnf", "Guinean franc"),
    GYD("gyd", "Guyanese dollar"),
    HTG("htg", "Haitian gourde"),
    HNL("hnl", "Honduran Lempira"),
    HKD("hkd", "Hong Kong Dollar"),
    HUF("huf", "Hungarian Forint"),
    ISK("isk", "Icelandic Krona"),
    INR("inr", "Indian Rupee"),
    IDR("idr", "Indonesian Rupiah"),
    IRR("irr", "Iranian rial"),
    IQD("iqd", "Iraqi dinar"),
    ILS("ils", "Israeli New Sheqel"),
    JMD("jmd", "Jamaican Dollar"),
    JOD("jod", "Jordanian Dinar"),
    KZT("kzt", "Kazakhstani Tenge"),
    KES("kes", "Kenyan shilling"),
    KWD("kwd", "Kuwaiti Dinar"),
    KGS("kgs", "Kyrgyzstan Som"),
    LAK("lak", "Lao kip"),
    LVL("lvl", "Latvian Lats"),
    LBP("lbp", "Lebanese Pound"),
    LSL("lsl", "Lesotho loti"),
    LRD("lrd", "Liberian dollar"),
    LYD("lyd", "Libyan Dinar"),
    LTL("ltl", "Lithuanian Litas"),
    MOP("mop", "Macanese pataca"),
    MKD("mkd", "Macedonian denar"),
    MGA("mga", "Malagasy ariary"),
    MWK("mwk", "Malawian kwacha"),
    MYR("myr", "Malaysian Ringgit"),
    MVR("mvr", "Maldivian rufiyaa"),
    MRO("mro", "Mauritanian Ouguiya"),
    MRU("mru", "Mauritanian ouguiya"),
    MUR("mur", "Mauritian Rupee"),
    MXN("mxn", "Mexican Peso"),
    MDL("mdl", "Moldova Lei"),
    MNT("mnt", "Mongolian togrog"),
    MAD("mad", "Moroccan Dirham"),
    MZN("mzn", "Mozambican metical"),
    MMK("mmk", "Myanma Kyat"),
    NAD("nad", "Namibian dollar"),
    NPR("npr", "Nepalese Rupee"),
    ANG("ang", "Neth.Antillean Guilder"),
    TWD("twd", "New Taiwan Dollar"),
    TMT("tmt", "New Turkmenistan Manat"),
    NZD("nzd", "New Zealand Dollar"),
    NIO("nio", "Nicaraguan Córdoba"),
    NGN("ngn", "Nigerian Naira"),
    NOK("nok", "Norwegian Krone"),
    OMR("omr", "Omani Rial"),
    PKR("pkr", "Pakistani Rupee"),
    PAB("pab", "Panamanian Balboa"),
    PGK("pgk", "Papua New Guinean kina"),
    PYG("pyg", "Paraguayan Guaraní"),
    PEN("pen", "Peruvian Nuevo Sol"),
    PHP("php", "Philippine Peso"),
    PLN("pln", "Polish Zloty"),
    QAR("qar", "Qatari Rial"),
    RON("ron", "Romanian New Leu"),
    RUB("rub", "Russian Rouble"),
    RWF("rwf", "Rwandan franc"),
    SVC("svc", "Salvadoran colon"),
    WST("wst", "Samoan tala"),
    STN("stn", "São Tomé and Príncipe Dobra"),
    SAR("sar", "Saudi Riyal"),
    RSD("rsd", "Serbian Dinar"),
    SCR("scr", "Seychelles rupee"),
    SLL("sll", "Sierra Leonean leone"),
    SGD("sgd", "Singapore Dollar"),
    SBD("sbd", "Solomon Islands dollar"),
    SOS("sos", "Somali shilling"),
    ZAR("zar", "South African Rand"),
    KRW("krw", "South Korean Won"),
    SSP("ssp", "South Sudanese pound"),
    LKR("lkr", "Sri Lanka Rupee"),
    SDG("sdg", "Sudanese pound"),
    SRD("srd", "Surinamese dollar"),
    SZL("szl", "Swazi lilangeni"),
    SEK("sek", "Swedish Krona"),
    SYP("syp", "Syrian pound"),
    TJS("tjs", "Tajikistan Ruble"),
    TZS("tzs", "Tanzanian shilling"),
    THB("thb", "Thai Baht"),
    TOP("top", "Tongan paʻanga"),
    TTD("ttd", "Trinidad Tobago Dollar"),
    TND("tnd", "Tunisian Dinar"),
    TRY("try", "Turkish Lira"),
    AED("aed", "U.A.E Dirham"),
    UGX("ugx", "Ugandan shilling"),
    UAH("uah", "Ukrainian Hryvnia"),
    UYU("uyu", "Uruguayan Peso"),
    UZS("uzs", "Uzbekistan Sum"),
    VUV("vuv", "Vanuatu vatu"),
    VES("ves", "Venezuelan Bolivar"),
    VND("vnd", "Vietnamese Dong"),
    XOF("xof", "West African CFA Franc"),
    YER("yer", "Yemeni rial"),
    ZMW("zmw", "Zambian kwacha");

    private String code;
    private String name;

    Currency(String code, String name) {
        this.code = code;
        this.name = name;
    }

    public String getCode() {
        return this.code;
    }

    @Override
    public String toString() {
        return String.format("%s (%s)", this.name(), this.name);
    }
}
